### ISSUE TITLE
Trackpad Support?

### ISSUE THREAD

**Issue by acramsay** [rianadon/Cosmos-Keyboards#1]
I've been testing out cosmos for a couple of days now. Super nice btw! I'd like to see a new "type" implemented to support [Cirque trackpads](https://www.cirque.com/glidepoint-circle-trackpads) and hopefully others. Basically, I'm thinking of a circular hole with attachment points.

**Comment by Lodrus** [comment]
Ahh I wish I could. But I don't have a printer. I've been planning to order a print after completing a design. I might be able to contribute in other ways. If you don't mind, I'll send you a private message.

**Comment by rianadon** [comment]
Trackpads in Cosmos are now a thing.

And now the first issue can be closed. Woohoo!
