### ISSUE TITLE
How can I add a custom size screen and keyswitches?

### ISSUE THREAD

**Issue by Trecoolius** [rianadon/Cosmos-Keyboards#18]
I want to add a screen that is a different size of what's offered. Also, I want to use a per-key PCB that I designed myself and that would require a different keyswich holder. What exactly is the workflow for custom parts? Also, what do I need to use to add this? SCAD, STL or STEP files?

**Comment by rianadon** [comment]
It's super possible to use your own parts. The parts section of the contributing docs](https://ryanis.cool/cosmos/docs/contributing/#contributing-parts) should have all the information you need for custom parts. You'll need STEP files for these.

Also, for displays, take a look at [`src/model_gen/parametric/display-gen.ts`](https://github.com/rianadon/Cosmos-Keyboards/blob/main/src/model_gen/parametric/display-gen.ts) and [`src/model_gen/parts.ts`](https://github.com/rianadon/Cosmos-Keyboards/blob/main/src/model_gen/parts.ts). The display sockets are simple enough that I have some code to parametrically generate them. You'll need to measure the `DisplayProps` in `display-gen.ts` then make your own variable `mydisplayDisplayProps` in `parts.ts` and call `genDisplayModel` and `genDisplaySocket` (basically, just copy what's there for the dfRobot display).

And once you've done all that, it would be super awesome if you'd like to create a Pull Request with them 😁

**Comment by Trecoolius** [comment]
Will totally do. I think with these super cheap pro micro RP2040's, the doors are open to using bigger and better displays. I will issue a PR when I finish testing my screen holder.
