### ISSUE TITLE
Key view changes when changing the thumb cluster from manuform to custom

### ISSUE THREAD

**Issue by maxbartel** [rianadon/Cosmos-Keyboards#7]
# Description
When changing the thumb cluster from manuform to custom, the `keys` view changes, while the 3D view does not. AFAIK the model does not change when going to custom, so I would expect the view not to change. 

The main problem is that the error check of the model seems to depend on that view. See this settings https://ryanis.cool/cosmos/beta#cf:ChYIBRAFWAAYBCADKNcBMM0BUAJAAEgAGgQIBhAA. When changing only the thumb cluster to custom, the error disappears.

# Screenshots
(all from the setting above)
View in manuform mode
![Screen Shot 2024-01-02 at 13 34 06 PM](https://github.com/rianadon/Cosmos-Keyboards/assets/6528731/b5e0bc2f-be36-4758-804a-9838c4eb1351)
Same in custom mode
![Screen Shot 2024-01-02 at 13 34 43 PM](https://github.com/rianadon/Cosmos-Keyboards/assets/6528731/f8a4f604-2b69-4b59-87a8-8855febcf461)

**Comment by rianadon** [comment]
Thanks for writing everything up! I didn't realize when you posted about this in Discord that the way the Manuform thumb cluster is being laid out is worse for layout than it's laid out in custom thumb cluster mode. My hope was really the reverse–that making the manuform cluster a little more flat in the 3D view would prevent collisions like this.

I'll take out the special processing that makes the Manuform mode look different from custom. That'll fix this!
